import Head from 'next/head'
import { Inter } from 'next/font/google'
import '@/styles/Home.module.css'
import Image from 'next/image'
import adidas from '@/public/adidas.png'
const inter = Inter({ subsets: ['latin'] })
import { useState } from 'react'

export default function Home() {
  const [xAxis, setXAxis] = useState<number>(0)
  const [yAxis, setYAxis] = useState<number>(0)
  const [transitionO, setTransitionO] = useState<string>('')

  function handleMove(e: any) {
    setXAxis((window.innerWidth / 2 - e.pageX) / 25)
    setYAxis((window.innerWidth / 2 - e.pageY) / 25)
  }

  function handleLeave() {
    setXAxis(0)
    setYAxis(0)
    setTransitionO('all 0.5s ease')
  }

  function handleEnter() {
    setXAxis(0)
    setYAxis(0)
    setTransitionO('none')
  }

  const containerStyle = {
    transform: `rotateY(${xAxis}deg) rotateX(${yAxis}deg)`,
    transition: transitionO,
  }

  return (
    <>
      <Head>
        <title>3D CARD</title>
        <meta name="3d card tutorial" content="Generated by yusha" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className="container"
          onMouseMove={(e) => handleMove(e)}
          onMouseLeave={() => {
            handleLeave()
          }}
          onMouseEnter={() => {
            handleEnter()
          }}
          style={containerStyle}
        >
          <div className="card">
            <div className="sneaker">
              <div className="circle"></div>
              <Image
                src={adidas}
                width={250}
                height={110}
                alt="adidas shoe"
              ></Image>
            </div>
            <div className="info">
              <h1 className="title">Adidas SUP1X</h1>
              <h3>
                FUTURE-READY TRAINERS WITH WRAPPED BOOST FOR EXCEPTION
                COMFORT.
              </h3>
              <div className="sizes">
                <button>35</button>
                <button className="active">36</button>
                <button>37</button>
                <button>38</button>
              </div>
              <div className="purchase">
                <button>Purchase</button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
